version: '3.8'

services:
  maria-landing-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - maria-network

networks:
  maria-network:
    driver: bridge